name: Percy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

jobs:
  percy:
    name: Visual testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: 15
    - name: Install
      run: yarn install --ignore-engines
    - name: Build
      run: yarn build
    - name: Start server and run percy
      run: |
        yarn start &
        sleep 60 &&
        yarn visual
      
